### ISSUE TITLE
Playlist handling – overwrite instead of append

### ISSUE THREAD

**Issue by Natenom** [MusicGenerator/mumble-ruby-pluginbot#125]
Lets say there is a playlist named "test".
Clear the current queue and add some new songs. Then save the current queue as a playlist that already exists:
.saveplaylist test

Now the bots appends all songs from the current queue to the already existing playlist and saves it.

Intead I would expect the bot to replace the old playlist with the current queue.

**Comment by dafoxia** [comment]
Behavior what I prefer to implement: If a playlist will saved and a playlist with same name exist already, the user is asked if he want to overwrite list or songs should be append.

Is this is ok for you?

**Comment by dafoxia** [comment]
Split in 2 commands with different behavior
