### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Natenom** [MusicGenerator/mumble-ruby-pluginbot#179]
100 65202    0 65202    0     0  29149      0 --:--:--  0:00:02 --:--:-- 29160curl: (28) Operation timed out after 3001 milliseconds with 65202 bytes received
2016-12-29 21:06:16 +0000 : Debug: Got a message from "Natenom" (user id: 111, session id: 123). Content: ".next"
/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/ruby-mpd-0.3.3/lib/ruby-mpd.rb:220:in `block in callback_thread': undefined method `[]=' for true:TrueClass (NoMethodError)

**Comment by dafoxia** [comment]
Is not reproduceable and occured the first time. 
Reopen if it crash again!
