### ISSUE TITLE
radio plugin crashes

### ISSUE THREAD

**Issue by Natenom** [MusicGenerator/mumble-ruby-pluginbot#185]
.clear
.radioupdate
.radioselect classic 1
.play

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    96    0    96    0     0    353      0 --:--:-- --:--:-- --:--:--   352
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  146k    0  146k    0     0  51236      0 --:--:--  0:00:02 --:--:-- 51245curl: (28) Operation timed out after 3000 milliseconds with 155015 bytes received
ERROR: An error occurred: wrong argument type nil (expected String)/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/ruby-mpd-0.3.3/lib/ruby-mpd.rb:220:in `block in callback_thread': undefined method `[]=' for true:TrueClass (NoMethodError)

**Comment by dafoxia** [comment]
Still can't reproduce. Used exact your commands. Please do a .queue before .play. Is there a link like 

> 0 http://listen.947thepoint.com:8000/wlyt

in?

**Comment by Natenom** [comment]
.queue
Docker_Test-Bot_Natenom: 

#
Name

0
http://listen.947thepoint.com:8000/range

**Comment by Natenom** [comment]
curl: (28) Operation timed out after 3000 milliseconds with 146953 bytes received
ERROR: An error occurred: wrong argument type nil (expected String)
ERROR: Backtrace: ["/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/opus-ruby-1.0.1/lib/opus-ruby/encoder.rb:88:in `put_string'", "/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/opus-ruby-1.0.1/lib/opus-ruby/encoder.rb:88:in `encode'", "/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/audio_player.rb:196:in `encode_sample'", "/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/audio_player.rb:178:in `produce'", "/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/thread_tools.rb:8:in `block (2 levels) in spawn_thread'", "/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/thread_tools.rb:8:in `loop'", "/home/botmaster/.rvm/gems/ruby-2.3.3@bots/gems/mumble-ruby-1.1.2/lib/mumble-ruby/thread_tools.rb:8:in `block in spawn_thread'"]

**Comment by Natenom** [comment]
This may be related to a bug in MPD (0.19.1) on Debian and there is a fix for that in 0.19.7/8.
