### ISSUE TITLE
extend gvalue to optional get a specific type of variable

### ISSUE THREAD

**Issue by Natenom** [MusicGenerator/mumble-ruby-pluginbot#194]
Conf.gvalue("plugin:idle:maxidletime", int)

instead of 

Conf.gvalue("plugin:idle:maxidletime").to_i

**Comment by dafoxia** [comment]
Untested and not implemented:
```
  def Conf.get_type(key, type)
    hash = @@configuration.clone
    key.split(':').each do |keyv|
      begin
        hash = hash[keyv]
      rescue
        nil
      end
    end
    return case type
      when Integer
        hash.to_i == Integer(hash) ? hash.to_i : nil
      when String
        hash.to_s == String(hash) ? hash.to_s : nil
      when Hash
        hash.to_h == hash ? hash : nil
      when Array
        hash.to_a == Array(hash) : nil
      else
        raise ArgumentError, "Type not known", caller
    end
      
  end
```
should be able to do things so:
`Conf.get_type("plugin:idle:maxidletime", Integer)`
which returns then the `value` or `nil` if it can convert or not, and throw an error if you will get a unknown type such as Banana.

But does this really improve something?

**Comment by Natenom** [comment]
Is the type parameter optional?
