### ISSUE TITLE
Error trying to run updater.sh

### ISSUE THREAD

**Issue by ibrudiiv** [MusicGenerator/mumble-ruby-pluginbot#206]
./updater.sh: line 47: `update_celt-gem': not a valid identifier
I realize it might be a variable environment issue, but nothing I've tried has worked, including source and verifying path issues.

**Comment by Natenom** [comment]
Line 47 is the end of "function update_celt-gem() {", see https://github.com/MusicGenerator/mumble-ruby-pluginbot/blob/master/scripts/updater.sh#L40

Do you run it with bash or with another shell like sh to which /bin/bash is a symlink to?

**Comment by ibrudiiv** [comment]
I was running it with sh until I figured out the issues with dashes. Works fine running it with bash.
Thanks for your reply :)
