### ISSUE TITLE
apostrophes in youtube video names cause the youtube-dl plugin to fail

### ISSUE THREAD

**Issue by jjfishtank** [MusicGenerator/mumble-ruby-pluginbot#228]
Hi, I'm running the virtualbox appliance for mumble ruby pluginbot.

It seems like whenever there is an apostrophe in a youtube video's title, the youtube-dl plugin fails and returns "this link contains nothing interesting." You can see this at line 95 in the attached log file (Video titled "We're Talking About...").

The error seems to be caused by line 85 in the YTDL.rb because the single quote in the filename is not escaped.
[bot1.zip](https://github.com/MusicGenerator/mumble-ruby-pluginbot/files/816005/bot1.zip)

**Comment by dafoxia** [comment]
That is a known problem to me and need some additional work to fix it right. As work arround you can set filename restriction to youtubedl. Names with possible problematic names are renamed with this settings.

Add `plugin: youtube: youtube_dl: options: "--restrict-filenames"` in your config.

Also see: http://mumble-ruby-pluginbot.readthedocs.io/en/master/explain_the_config.html#youtube-plugin-settings

**Comment by Niichie** [comment]
Having this issue as well, trying to figure out how to add the restrict filenames option to my plugin config but I can't seem to get it to work. Is there a screenshot of what the completed file should look like?
![1](https://cloud.githubusercontent.com/assets/16381287/26278604/c2f4afd8-3d6c-11e7-9f73-a3150dd0a987.PNG)

**Comment by dafoxia** [comment]
You wrote 
`"--restrict-filnames"` 
instead of 
`"--restrict-filenames"`

;)

**Comment by Niichie** [comment]
Hello I fixed the typo in the youtube.yml file but I'm still getting the "this link contains nothing interesting" error from the bot.
![3](https://cloud.githubusercontent.com/assets/16381287/26378857/50406d36-3fe4-11e7-860f-0ddd6b4d8b1d.PNG)

**Comment by dafoxia** [comment]
Please post your log. The message can also occure if the content is not aviable in your country or you have to solve a capture for youtube.

**Comment by PsikoBlock** [comment]
Getting the same issue:

> 2017-06-02 01:10:33 +0200 : Debug: Got a message from "Psiko" (user id: 1, session id: 15). Content: ".ytlink <a href="https://www.youtube.com/watch?v=ymNFyxvIdaM">https://www.youtube.com/watch?v=ymNFyxvIdaM</a>"
2017-06-02 01:10:33 +0200 : INFO: Youtube start Thread for Psiko.
W, [2017-06-02T01:10:24.172618 #14754]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#key defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-06-02T01:10:24.174387 #14754]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#hash defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-06-02T01:10:24.174763 #14754]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#hash defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-06-02T01:10:24.174935 #14754]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#hash defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
W, [2017-06-02T01:10:24.175173 #14754]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#hash defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
sh: 1: Syntax error: Unterminated quoted string
2017-06-02 01:10:38 +0200 : INFO: Youtube end Thread for Psiko.

**Comment by berksaribas** [comment]
I have the exact same problem with apostrophes and ` "--restrict-filnames"` doesn't seem to solve the problem. I am getting the same errors as @PsikoBlock

**Comment by dafoxia** [comment]
@Niichie : You should edit your bot config instead the config shipped with the plugin.
Use updater.sh when you run just one bot to edit the right file and add there.
`plugin:
  youtube:
    youtube_dl:
      options: "--restrict-filenames"
`
@PsikoBlock and @berksaribas : I could'nt reproduce your warnings in the log. Please give me more input about rvm version and installed ruby gems if your installation differ from the [official guide](http://mumble-ruby-pluginbot.readthedocs.io/en/master/)

**Comment by ThatBrickster** [comment]
@dafoxia : "--restrict-filenames" only works for ampersands and underscores in addition to stripping out non-ASCII characters.

I don't have the syntax error in my log either but any time someone does request a link with an apostrophe in the title I have to restart the bot.

**Comment by psychosillex** [comment]
@dafoxia I know this is super old but I just setup your bot for my mumble users on RedHat7 and with 4 or 5 people quickly putting this through the ringer I came across the dreaded "apostrophe in the title" issue.  I tired the restricted files workaround without success like others reported.  Was there ever a fix or a different workaround?

**Comment by psychosillex** [comment]
Will test it out this evening and report back with my findings.  Thanks for
taking some of your time!

**Comment by psychosillex** [comment]
@dafoxia  sorry it took a lot longer to get to it than expected.  It did not work however.

**Comment by dafoxia** [comment]
Same issue as #241.
Please see there for more information.
