### ISSUE TITLE
"Connection timed out" after following official installation document on arm-hf Linux

### ISSUE THREAD

**Issue by RedFantom** [MusicGenerator/mumble-ruby-pluginbot#229]
After following the official installation document I found [here](http://mumble-ruby-pluginbot.readthedocs.io/en/master/installation_howto.html) on an Orange Pi running Armbian (Ubuntu 16.04.2 arm-hf) to the letter, I get the following output to `bot1.log` when running the start command:

```
2017-04-10 17:12:13 +0000 : OK: Connecting to the server is still ongoing.
2017-04-10 17:12:14 +0000 : OK: Connecting to the server is still ongoing.
2017-04-10 17:12:14 +0000 : OK: Connecting to the server is still ongoing.
2017-04-10 17:12:14 +0000 : Error: Connection timed out
```

When following the guide on a Raspberry Pi B+ running Raspbian, the result is the same. However, when I follow the exact same steps on a Ubuntu 16.04 virtual machine, everything goes as planned and the result is as expected, even when using the same mumble server, password and username to connect to the server. The log files are *exactly* the same (for as far as I can tell) up until the line `OK: Pluginbot is running.` is printed. After this, the arm-hf machine prints the log snippet above, and the VM prints to the log file that it successfully connected and some other things.

What I gather from this is that there is some kind of connection issue on arm-hf devices, which is strange, because there are other users running on a Raspberry Pi 2B, right?

Other information that might be important:

- Ruby had to be compiled on the arm-hf devices, compiled version 2.4.0 and installed it (that's the latest one)
- I'm trying to run just a single bot
- The script is run as the correct user
- I've done everything twice on the Raspberry Pi B+ (I know it can't run it smoothly, but it should connect), following all instructions to the letter, with the same result, as well as when trying on the Orange Pi PC
- One of test servers is located on `localhost`
- No iptables or other firewall software was used
- I use domains to connect

Thank you for your time!

**Comment by dafoxia** [comment]
The message `Date/Time : OK: Connecting to the server is still ongoing.` should displayed on the log 10 times. The time difference between first and last message should be around 5 seconds. 
The server should authenticate in this time running on a normal machine. If the server runs on a small ARM-Device too, the device is maybe to slow.

The installation is tested on a banana pi, banana pi m2 running on Armbian, on Raspberry Pi 2/3 on Debian wheezy successful.

There are ready to download images for Banana Pi / Raspberry Pi 2/3 running on Arch-Linux. You could test these to verify there is no other error in your settings.

If problem persist, please post your configuration and I will test it on my Hardware (Pi2).

**Comment by RedFantom** [comment]
That is indeed what was in the log file. However, I have it working now. Apparently, you can't use special characters in the Mumble username, so now I feel stupid. Still, thank you for the help and your time, now I can go and enjoy your great software :) .

**Comment by dafoxia** [comment]
You can use special characters in mumble. By default they are restricted in server configuration. :)
