### ISSUE TITLE
MumbleRubyPluginBot on CentOS 7

### ISSUE THREAD

**Issue by TheEight-BitLink** [MusicGenerator/mumble-ruby-pluginbot#230]
I've gotten MRPB to run on CentOS 7 just fine with four bots and the version of Murmur included in nux-dextop repository. The command to install the necessary packages for building is `yum install libyaml opus-tools wget aria2 libyaml-devel git opus-devel zlib zlib-devel openssl-devel mpd libmpc tmux automake autoconf libtool libogg-devel gmp-devel dialog unzip bzip2`. Similarly, for Youtube-dl, the command is `yum install ImageMagick python ffmpeg`. Note the capitalization is important: without it, yum reports it can't find imagemagick and suggests installing ImageMagick.

**Comment by dafoxia** [comment]
Thanks for your report! We will add this to the documentation.

**Comment by Natenom** [comment]
Thank you much :) 

I added your information to the installation howto and to the compatibilty list.
