### ISSUE TITLE
Radio on pause

### ISSUE THREAD

**Issue by preterive** [MusicGenerator/mumble-ruby-pluginbot#233]
Hello,
i have automute activated. if nobody is in the chanel it set mpd to pause and not to stop.
The Radio has more then 2 days delay. i have to start it new every few days with .playlist 0

**Comment by Natenom** [comment]
Can you please provide the output of .version ?

As far as I remember the bot should stop a stream on mute in the latest version.

**Comment by Natenom** [comment]
Ok, just looked into the code. The bot does a stop if a stream is played only if an unregistered user enters the current channel, but not on automute when he is alone.

**Comment by Natenom** [comment]
working on it

**Comment by Natenom** [comment]
See http://mumble-ruby-pluginbot.readthedocs.io/en/master/how_to_run_the_bot.html?highlight=update#automatic-update how to update your bot :)

**Comment by preterive** [comment]
Thank you.
