### ISSUE TITLE
manage.sh mpd pid parsing issue

### ISSUE THREAD

**Issue by oCanna** [MusicGenerator/mumble-ruby-pluginbot#236]
Hello,

`mpdpid=$(ps aux | grep -i mpd | grep -v grep | grep -E "mpd.*mpd${botid}" | cut -d" " -f2)`

doesn't work for me. I would suggest using awk instead of cut.

`mpdpid=$(ps aux | grep -i mpd | grep -v grep | grep -E "mpd.*mpd${botid}" | awk '{ print $2 }')`

**Comment by dafoxia** [comment]
Please post your system. We will test this on your distribution ane will find a solution or write a tip on the manual. Alternative we will check our tested distributions and add if necessary a awk package to the guide and patch the bot.
Thanks.

**Comment by oCanna** [comment]
Ubuntu 16.04.3 and procps-ng version 3.3.9

The problem is, that  sometimes the space between the username and the process-id is more than one char long in which case 'cut' fails.

An other solution would be "ps ax" instead of "ps aux".
`mpdpid=$(ps ax | grep -i mpd | grep -v grep | grep -E "mpd.*mpd${botid}" |  cut -d" " -f1`

**Comment by oCanna** [comment]
Sorry for the inconvenience, but as I've tested the setup on an other machine running ubuntu 16.04.3 I noticed that 'cut' still does fail if there is a space in front of the pid. I think using awk would be the best solution because it doesn't care about space characters.
