### ISSUE TITLE
Adding youtube video with certain title fails

### ISSUE THREAD

**Issue by GamerBene19** [MusicGenerator/mumble-ruby-pluginbot#241]
First of all: Thanks for this awesome bot. I've been using it on my own server for quite a long time now and I really like it.

Unfortunately today I encountered a bug, that breaks downloading (or more precisely **adding** videos) from YT to the music directory of the bot.

I tried adding [this song](https://www.youtube.com/watch?v=w15oWDh02K4) and it appears that sth in the video title (my guess would be the singlequotes/apostrophes) breaks the downloading and adding procedure of the bot.

### What i did:
I added a few other songs, and they worked just fine.
I then tried adding above song and it gets downloaded into the temp folder just fine, but it doesn't get moved to the music directory afterwards (like every other song).

Also from this point on adding songs that worked previously, appears to be broken as well (Although for those songs it can be fixed by restarting the bot)

I think this could be related to [#228](https://github.com/MusicGenerator/mumble-ruby-pluginbot/issues/228), but I'm not 100% sure, as in my case files seem to get **downloaded** by youtube-dl just not moved/added.

**Comment by dafoxia** [comment]
This is an issue with uncorrect escaping for the shell.
The error is located in /helpers/YTDL.rb after line 70.
Should be handled in line 73 or, if that is'nt possible in line 85, 88 and  95.

**Comment by GamerBene19** [comment]
Thanks for the quick answer. I already thought it was because of something like this, but couldn't find where it would be.

Unfortunately I don't know Ruby though. So I've a few questions...
What shell command (in the "exe" variable) is used in line 73?
Could you tell me what I'd have to do to debug the file (to understand what changes do) or - ideally - which changes I would have to make to the line(s) to make it work 'properly'?

Thanks for your help!

**Comment by ZeroPoke** [comment]
So I actually have a patched version that works.  My friend fixed it for me.  I dont know Ruby so I dont know what he did.  Hell I dont know if he edited any other files....

https://gist.github.com/ZeroPoke/f56cedecfcedcc7060f0ede5fbc2e860

**Comment by GamerBene19** [comment]
Soo... I just replaced the original file with the one from @ZeroPoke yesterday and now adding videos with single quotes in the title (like the song I used) works as expected.
I consider this issue closed for now, because it has been resolved (for me).
To the authors/maintainers of this repo: Could you update the file in order to fix this issue permanently?

Thanks for the quick and easy help!

**Comment by dafoxia** [comment]
Will fix this in our repository, but code is written by an unknown author to me, there I've to clarify if the changes are in compatibility with our licence. (MIT)

If not we have fix this in a other way.

**Comment by TheDgtl** [comment]
I'm the guy who wrote the changes ZeroPoke is running. The changes are licensed under the MIT license, so have at them :)

**Comment by dafoxia** [comment]
Thanks, will add this at the evening.
