### ISSUE TITLE
Add option for mpd password

### ISSUE THREAD

**Issue by lnjX** [MusicGenerator/mumble-ruby-pluginbot#243]
I'd like to set a password in the bot configuration that should be used when connecting to mpd.

**Comment by dafoxia** [comment]
I was wrong.
Sleeping a night and remembering howto code in ruby bring some light in my darkened head. :)

Please do a git pull and don't forget to set a password in your bot config.

    plugin:
      mpd:
        volume: 65
        host: localhost
        port: 7701
        password: ''
      idle:
        maxidletime: 600
        idleaction: 'channel'

**Comment by lnjX** [comment]
Oh thank you very much! That's great. :tada:
