### ISSUE TITLE
Cannot add songs manually

### ISSUE THREAD

**Issue by gittigy** [MusicGenerator/mumble-ruby-pluginbot#245]
I've read that songs can be manually added by simply copying the song files to the "/home/botmaster/music/downloadedfromyt" or any other similar music directory and an ".update" command ran. Log shows the files are "found" when the update command is issued but the manually added songs cannot be added to the playlist to be played. Songs are not returned when ".where [filename]" command is issued.

I feel there's probably some steps I'm missing. Can songs be added manually? If so, how exactly?

**Comment by dafoxia** [comment]
The Bot use MPD as music-player-engine. MPD itself use a database where it stores information to the music files. If the music files contain tags, this tags are stored in the database to find the right file.
Test it with ".where [songname]. 
This behavior confuses a lot of people :)

**Comment by FennyFatal** [comment]
Personally, I have found success pairing the bot with a Web UI to control
MPD. Makes it easy to find the right file.

This is the one I use if you are interested:
https://www.ympd.org/

**Comment by gittigy** [comment]
Thank you for your comments dafoxia & FennyFatal. You were correct about the tags and the database. The reason the files I manually added were not being allowed to be added to the queue was because the "Title" tag field was empty on the files I manually added. I used a small tag editor software (may not even be needed) to edit the title tag field and ran .update again and was able to add the song to the queue and play it. Just what I wanted!

I also setup ympd and enjoy the option to control mpd from a browser as some users have sounds set in mumble when messages (commands) are issued and ympd allows seamless control of mpd without spamming mumble chat and possibly disturbing mumble members.  Really cool and easy to setup!

Thanks so much for the comments/info and for the great software in general. We've used this music bot for several years now. If regular users join the server and don't see the "MumbleDJ", literally every one of them asks "where is MumbleDJ!?" It's become a part of the server and we are always grateful to have it. Thanks again!

**Comment by dafoxia** [comment]
You made me very happy and proud today with your joyful post. This are the reasons why I made this open source and free for all. In real life work the people around me are in general pissed when I want to make things better work.
Every opend issue let me know a user use this project and I can do something to make it better.
I've to thank you and every other who use this software, opend an Issue, commenting something to or fix bugs or write new plugins to.
Have also a look at the people who forked this, there are some interesting plugins to find on their repositorys.
:D
