### ISSUE TITLE
Starting the bot fails (error message below)

### ISSUE THREAD

**Issue by GamerBene19** [MusicGenerator/mumble-ruby-pluginbot#246]
After (what seems like) a successful installation following the tutorial [here](https://mumble-ruby-pluginbot.readthedocs.io/en/master/installation_howto.html#installationonyourown-label) starting the bot fails with the following error message (in the log)

```
<internal:/home/botmaster/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- mumble-ruby (LoadError)
        from <internal:/home/botmaster/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/botmaster/src/mumble-ruby-pluginbot/core/pluginbot.rb:6:in `<main>'
```

My installation was on a fresh and up-to-date copy of Ubuntu 20.04. If additional info is needed, just let me know

**Comment by dafoxia** [comment]
It seem that something went wrong when you build the mumble-pruby gem.
Please do the steps in "**Get and build mumble-ruby and ruby-mpd and other dependencies**" for the mumble-ruby gem again and retry.

**Comment by GamerBene19** [comment]
I "restarted" (as in I redid the steps from there on) the tutorial from your mentioned section. When entering the mumble-ruby directory I got the following output in the terminal:
```
botmaster@mumbleBots:~/src$ cd mumble-ruby
Required ruby-2.1.1 is not installed.
To install do: 'rvm install "ruby-2.1.1"'
```
I then executed said command with 
`botmaster@mumbleBots:~/src/mumble-ruby$ rvm install "ruby-2.1.1"`
During which I got the following warning/error (installation did continue):
`Libraries missing for ruby-2.1.1: libcrypto.so.1.0.0,libssl.so.1.0.0. Refer to your system manual for installing libraries`
At the end of the installation I also got the following error:
```
Error running 'env GEM_HOME=/home/botmaster/.rvm/gems/ruby-2.1.1@global GEM_PATH= /home/botmaster/.rvm/rubies/ruby-2.1.1/bin/ruby -d /home/botmaster/.rvm/src/rubygems-3.0.9/setup.rb --no-document',
please read /home/botmaster/.rvm/log/1617653973_ruby-2.1.1/rubygems.install.log
```
And now upon reentering the mumble-ruby directory the console output looks like: 
```
botmaster@mumbleBots:~/src/mumble-ruby$ cd ..
botmaster@mumbleBots:~/src$ cd mumble-ruby
ruby-2.1.1 - #gemset created /home/botmaster/.rvm/gems/ruby-2.1.1@mumble_ruby_gem
ruby-2.1.1 - #generating mumble_ruby_gem wrappers.................
Error running 'run_gem_wrappers regenerate',
please read /home/botmaster/.rvm/log/1617654238_ruby-2.1.1/gemset.wrappers.mumble_ruby_gem.log
```

If needed I can also provide the two .log-files, just let me know. Thanks in advance for the help!

**Comment by dafoxia** [comment]
There is no need to use the older Ruby-2.1.1 it should work just fine at ruby 3.0.0 [just tested] :)
do a `rvm use @bots` and then a  `which ruby`
If you get there ruby-2.1.1 or similar and not ruby-3.0.0 then please do a `rvm remove ruby-2.1.1` and then `rvm reinstall ruby-3.0.0`, check if `which ruby` print out version 3.0.0, if not do a web-search with "rvm list" and "rvm set default"
--------------------------
After this you should do all points in the tuturial starting and including the point "Setting up a Ruby environment".
Ignore the outputs you get, do it stupid with copy and paste. The bot really need some work on it's gems, this is why you get sometimes confusing information. :P Hoping I got some time and passion in future to work on this.

Do all steps without hurry and rush. Take the time it take and you will get a stuttering bot. :)
Then open `~/mpd/mpd.conf` with your favorite editor and set the hashtag in the line format to the other line.

**Comment by GamerBene19** [comment]
So. I got the bot itself up and running now (I did do what is described [here](https://stackoverflow.com/questions/64653051/make-usr-bin-mkdir-command-not-found-during-gem-install-nokogiri-in-ubuntu)) I think that is/was the cause of the problem.

Now my bot is up and running, but not connecting to the server. The server's log says something about an unsuccessful SSL handshake (see below). Have you got any ideas what this is caused by?
```
<W>2021-04-06 23:12:38.684 1 => <43:(-1)> New connection: 10.0.12.110:55378
<W>2021-04-06 23:12:38.688 1 => <43:(-1)> Connection closed: Error during SSL handshake: error:140940F4:SSL routines:ssl3_read_bytes:unexpected message [13]
<W>2021-04-06 23:12:40.084 Ignored OpenSSL error 140E0197 for 0x55a3f2545a80
```
Thanks again for all your help, really appreciate it!

**Comment by dafoxia** [comment]
I've not seen this error unil yet. Please try an other username for the bot. The only thing I can imagine is a certification missmatch.

**Comment by GamerBene19** [comment]
Sorry for answering so late. I got a bit distracted. I did try out a different username. Still got the same error.

Do you have any idea what could lead to this error? Or how to diagnose it?

**Comment by dafoxia** [comment]
Sorry, no idea. :/

**Comment by GamerBene19** [comment]
Hey, sorry to dig this issue up again.
I decided to give installing (or should I say starting) the bot another try.

Unfortunately I'm facing the same error as earlier this year...
I was wondering if that issue is because of something that is misconfigured on my end or if it is somthing that is wrong with the repo itself. Could you maybe try to reproduce it to see if it is because of me or something else?

Could it be that there have been some changes to murmur regarding encryption/SSL that require changes in this repo?
If so, are you/the other maintainers of this repo willing to investigate?

**Comment by dafoxia** [comment]
https://github.com/dafoxia/mumble-ruby/commit/f0529e251efc7f989794f6dcf2ca1991a4d7b773
fixes the encryption error bug.
Simply update your mumble-ruby gem, it should work now again. 
(Sorry for the long time it needs to fix this)

**Comment by GamerBene19** [comment]
Yes, I just tried it out (did reinstall the bot on my new server) and it worked perfectly. Thanks for the fix!
